name: CI/CD with GitHub Actions

# Define when to trigger the workflow (on each push to the main branch)
## Whatever push changes occurs to main branch, this workflow will trigger.
on:
  push:
    branches:
      - main 
  workflow_dispatch: # For Mannual Trigger

jobs:
  BuildRelease:
    # Set the environment for this job (place where these workflow will run below steps and cmds)
    runs-on: ubuntu-latest
    steps:
      #checkout to current branch (in this case 'main' branch)
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      # Use the setup-java action to configure the Java environment
      - name: 'Set up JDK 11'
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Run Maven command to build the project
      - name: Build with Maven
        run: mvn clean install -Dmaven.test.skip=true --file ./pom.xml

      # Use the softprops/action-gh-release action to create a GitHub release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.1
          files: target/my-app-1.0-SNAPSHOT.jar # Specify the files to be included in the release (JAR files in the target directory)
          token: ${{ secrets.GIT_BOT_RAMI }} # Stored the access token as a GitHub action secret.
